name: "Task 1: Terraform CI/CD"

on:
  push:
    branches:
      - main
    paths:
      - 'task1/**'
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Deploy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task1

    env:
      TF_VAR_do_token: ${{ secrets.DO_PAT }}
      TF_VAR_spaces_access_id: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      TF_VAR_spaces_secret_key: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -backend-config="bucket=vtushn-tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
